// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/carrier/auth_handshake.proto

package carrier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WireNodeCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertVersion   uint32                 `protobuf:"varint,1,opt,name=cert_version,json=certVersion,proto3" json:"cert_version,omitempty"`
	NodePubKey    []byte                 `protobuf:"bytes,2,opt,name=node_pub_key,json=nodePubKey,proto3" json:"node_pub_key,omitempty"`
	IssuerCaHash  string                 `protobuf:"bytes,3,opt,name=issuer_ca_hash,json=issuerCaHash,proto3" json:"issuer_ca_hash,omitempty"`
	ValidFrom     int64                  `protobuf:"varint,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil    int64                  `protobuf:"varint,5,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Serial        []byte                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	CertNonce     []byte                 `protobuf:"bytes,7,opt,name=cert_nonce,json=certNonce,proto3" json:"cert_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireNodeCert) Reset() {
	*x = WireNodeCert{}
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireNodeCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireNodeCert) ProtoMessage() {}

func (x *WireNodeCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireNodeCert.ProtoReflect.Descriptor instead.
func (*WireNodeCert) Descriptor() ([]byte, []int) {
	return file_proto_carrier_auth_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *WireNodeCert) GetCertVersion() uint32 {
	if x != nil {
		return x.CertVersion
	}
	return 0
}

func (x *WireNodeCert) GetNodePubKey() []byte {
	if x != nil {
		return x.NodePubKey
	}
	return nil
}

func (x *WireNodeCert) GetIssuerCaHash() string {
	if x != nil {
		return x.IssuerCaHash
	}
	return ""
}

func (x *WireNodeCert) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *WireNodeCert) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *WireNodeCert) GetSerial() []byte {
	if x != nil {
		return x.Serial
	}
	return nil
}

func (x *WireNodeCert) GetCertNonce() []byte {
	if x != nil {
		return x.CertNonce
	}
	return nil
}

type WireDelegationProof struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TlsCertPubKeyHash  []byte                 `protobuf:"bytes,1,opt,name=tls_cert_pub_key_hash,json=tlsCertPubKeyHash,proto3" json:"tls_cert_pub_key_hash,omitempty"`
	TlsExporterBinding []byte                 `protobuf:"bytes,2,opt,name=tls_exporter_binding,json=tlsExporterBinding,proto3" json:"tls_exporter_binding,omitempty"`
	TlsTranscriptHash  []byte                 `protobuf:"bytes,3,opt,name=tls_transcript_hash,json=tlsTranscriptHash,proto3" json:"tls_transcript_hash,omitempty"`
	X509Fingerprint    []byte                 `protobuf:"bytes,4,opt,name=x509_fingerprint,json=x509Fingerprint,proto3" json:"x509_fingerprint,omitempty"`
	NodeCertBundleHash []byte                 `protobuf:"bytes,5,opt,name=node_cert_bundle_hash,json=nodeCertBundleHash,proto3" json:"node_cert_bundle_hash,omitempty"`
	NotBefore          int64                  `protobuf:"varint,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter           int64                  `protobuf:"varint,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WireDelegationProof) Reset() {
	*x = WireDelegationProof{}
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireDelegationProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireDelegationProof) ProtoMessage() {}

func (x *WireDelegationProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireDelegationProof.ProtoReflect.Descriptor instead.
func (*WireDelegationProof) Descriptor() ([]byte, []int) {
	return file_proto_carrier_auth_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *WireDelegationProof) GetTlsCertPubKeyHash() []byte {
	if x != nil {
		return x.TlsCertPubKeyHash
	}
	return nil
}

func (x *WireDelegationProof) GetTlsExporterBinding() []byte {
	if x != nil {
		return x.TlsExporterBinding
	}
	return nil
}

func (x *WireDelegationProof) GetTlsTranscriptHash() []byte {
	if x != nil {
		return x.TlsTranscriptHash
	}
	return nil
}

func (x *WireDelegationProof) GetX509Fingerprint() []byte {
	if x != nil {
		return x.X509Fingerprint
	}
	return nil
}

func (x *WireDelegationProof) GetNodeCertBundleHash() []byte {
	if x != nil {
		return x.NodeCertBundleHash
	}
	return nil
}

func (x *WireDelegationProof) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *WireDelegationProof) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

type WireEmbeddedCA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PubKem        []byte                 `protobuf:"bytes,2,opt,name=pub_kem,json=pubKem,proto3" json:"pub_kem,omitempty"`
	PubSign       []byte                 `protobuf:"bytes,3,opt,name=pub_sign,json=pubSign,proto3" json:"pub_sign,omitempty"`
	AnchorSig     []byte                 `protobuf:"bytes,4,opt,name=anchor_sig,json=anchorSig,proto3" json:"anchor_sig,omitempty"`
	AnchorAdmin   string                 `protobuf:"bytes,5,opt,name=anchor_admin,json=anchorAdmin,proto3" json:"anchor_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireEmbeddedCA) Reset() {
	*x = WireEmbeddedCA{}
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireEmbeddedCA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireEmbeddedCA) ProtoMessage() {}

func (x *WireEmbeddedCA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireEmbeddedCA.ProtoReflect.Descriptor instead.
func (*WireEmbeddedCA) Descriptor() ([]byte, []int) {
	return file_proto_carrier_auth_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *WireEmbeddedCA) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WireEmbeddedCA) GetPubKem() []byte {
	if x != nil {
		return x.PubKem
	}
	return nil
}

func (x *WireEmbeddedCA) GetPubSign() []byte {
	if x != nil {
		return x.PubSign
	}
	return nil
}

func (x *WireEmbeddedCA) GetAnchorSig() []byte {
	if x != nil {
		return x.AnchorSig
	}
	return nil
}

func (x *WireEmbeddedCA) GetAnchorAdmin() string {
	if x != nil {
		return x.AnchorAdmin
	}
	return ""
}

type WireAuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certs         []*WireNodeCert        `protobuf:"bytes,1,rep,name=certs,proto3" json:"certs,omitempty"`
	CaSignatures  [][]byte               `protobuf:"bytes,2,rep,name=ca_signatures,json=caSignatures,proto3" json:"ca_signatures,omitempty"`
	Authorities   []*WireEmbeddedCA      `protobuf:"bytes,3,rep,name=authorities,proto3" json:"authorities,omitempty"`
	Delegation    *WireDelegationProof   `protobuf:"bytes,4,opt,name=delegation,proto3" json:"delegation,omitempty"`
	DelegationSig []byte                 `protobuf:"bytes,5,opt,name=delegation_sig,json=delegationSig,proto3" json:"delegation_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireAuthMessage) Reset() {
	*x = WireAuthMessage{}
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireAuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireAuthMessage) ProtoMessage() {}

func (x *WireAuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_auth_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireAuthMessage.ProtoReflect.Descriptor instead.
func (*WireAuthMessage) Descriptor() ([]byte, []int) {
	return file_proto_carrier_auth_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *WireAuthMessage) GetCerts() []*WireNodeCert {
	if x != nil {
		return x.Certs
	}
	return nil
}

func (x *WireAuthMessage) GetCaSignatures() [][]byte {
	if x != nil {
		return x.CaSignatures
	}
	return nil
}

func (x *WireAuthMessage) GetAuthorities() []*WireEmbeddedCA {
	if x != nil {
		return x.Authorities
	}
	return nil
}

func (x *WireAuthMessage) GetDelegation() *WireDelegationProof {
	if x != nil {
		return x.Delegation
	}
	return nil
}

func (x *WireAuthMessage) GetDelegationSig() []byte {
	if x != nil {
		return x.DelegationSig
	}
	return nil
}

var File_proto_carrier_auth_handshake_proto protoreflect.FileDescriptor

const file_proto_carrier_auth_handshake_proto_rawDesc = "" +
	"\n" +
	"\"proto/carrier/auth_handshake.proto\x12\acarrier\"\xf0\x01\n" +
	"\fWireNodeCert\x12!\n" +
	"\fcert_version\x18\x01 \x01(\rR\vcertVersion\x12 \n" +
	"\fnode_pub_key\x18\x02 \x01(\fR\n" +
	"nodePubKey\x12$\n" +
	"\x0eissuer_ca_hash\x18\x03 \x01(\tR\fissuerCaHash\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x05 \x01(\x03R\n" +
	"validUntil\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\fR\x06serial\x12\x1d\n" +
	"\n" +
	"cert_nonce\x18\a \x01(\fR\tcertNonce\"\xc3\x02\n" +
	"\x13WireDelegationProof\x120\n" +
	"\x15tls_cert_pub_key_hash\x18\x01 \x01(\fR\x11tlsCertPubKeyHash\x120\n" +
	"\x14tls_exporter_binding\x18\x02 \x01(\fR\x12tlsExporterBinding\x12.\n" +
	"\x13tls_transcript_hash\x18\x03 \x01(\fR\x11tlsTranscriptHash\x12)\n" +
	"\x10x509_fingerprint\x18\x04 \x01(\fR\x0fx509Fingerprint\x121\n" +
	"\x15node_cert_bundle_hash\x18\x05 \x01(\fR\x12nodeCertBundleHash\x12\x1d\n" +
	"\n" +
	"not_before\x18\x06 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\a \x01(\x03R\bnotAfter\"\x9a\x01\n" +
	"\x0eWireEmbeddedCA\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\apub_kem\x18\x02 \x01(\fR\x06pubKem\x12\x19\n" +
	"\bpub_sign\x18\x03 \x01(\fR\apubSign\x12\x1d\n" +
	"\n" +
	"anchor_sig\x18\x04 \x01(\fR\tanchorSig\x12!\n" +
	"\fanchor_admin\x18\x05 \x01(\tR\vanchorAdmin\"\x83\x02\n" +
	"\x0fWireAuthMessage\x12+\n" +
	"\x05certs\x18\x01 \x03(\v2\x15.carrier.WireNodeCertR\x05certs\x12#\n" +
	"\rca_signatures\x18\x02 \x03(\fR\fcaSignatures\x129\n" +
	"\vauthorities\x18\x03 \x03(\v2\x17.carrier.WireEmbeddedCAR\vauthorities\x12<\n" +
	"\n" +
	"delegation\x18\x04 \x01(\v2\x1c.carrier.WireDelegationProofR\n" +
	"delegation\x12%\n" +
	"\x0edelegation_sig\x18\x05 \x01(\fR\rdelegationSigB-Z+github.com/i5heu/ouroboros-db/proto/carrierb\x06proto3"

var (
	file_proto_carrier_auth_handshake_proto_rawDescOnce sync.Once
	file_proto_carrier_auth_handshake_proto_rawDescData []byte
)

func file_proto_carrier_auth_handshake_proto_rawDescGZIP() []byte {
	file_proto_carrier_auth_handshake_proto_rawDescOnce.Do(func() {
		file_proto_carrier_auth_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_carrier_auth_handshake_proto_rawDesc), len(file_proto_carrier_auth_handshake_proto_rawDesc)))
	})
	return file_proto_carrier_auth_handshake_proto_rawDescData
}

var file_proto_carrier_auth_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_carrier_auth_handshake_proto_goTypes = []any{
	(*WireNodeCert)(nil),        // 0: carrier.WireNodeCert
	(*WireDelegationProof)(nil), // 1: carrier.WireDelegationProof
	(*WireEmbeddedCA)(nil),      // 2: carrier.WireEmbeddedCA
	(*WireAuthMessage)(nil),     // 3: carrier.WireAuthMessage
}
var file_proto_carrier_auth_handshake_proto_depIdxs = []int32{
	0, // 0: carrier.WireAuthMessage.certs:type_name -> carrier.WireNodeCert
	2, // 1: carrier.WireAuthMessage.authorities:type_name -> carrier.WireEmbeddedCA
	1, // 2: carrier.WireAuthMessage.delegation:type_name -> carrier.WireDelegationProof
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_carrier_auth_handshake_proto_init() }
func file_proto_carrier_auth_handshake_proto_init() {
	if File_proto_carrier_auth_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_carrier_auth_handshake_proto_rawDesc), len(file_proto_carrier_auth_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_carrier_auth_handshake_proto_goTypes,
		DependencyIndexes: file_proto_carrier_auth_handshake_proto_depIdxs,
		MessageInfos:      file_proto_carrier_auth_handshake_proto_msgTypes,
	}.Build()
	File_proto_carrier_auth_handshake_proto = out.File
	file_proto_carrier_auth_handshake_proto_goTypes = nil
	file_proto_carrier_auth_handshake_proto_depIdxs = nil
}
