// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/carrier/heartbeat.proto

package carrier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatNodeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatNodeEntry) Reset() {
	*x = HeartbeatNodeEntry{}
	mi := &file_proto_carrier_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNodeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNodeEntry) ProtoMessage() {}

func (x *HeartbeatNodeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNodeEntry.ProtoReflect.Descriptor instead.
func (*HeartbeatNodeEntry) Descriptor() ([]byte, []int) {
	return file_proto_carrier_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatNodeEntry) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *HeartbeatNodeEntry) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *HeartbeatNodeEntry) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type HeartbeatPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SentAtUnix       int64                  `protobuf:"varint,1,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	SenderRole       int32                  `protobuf:"varint,2,opt,name=sender_role,json=senderRole,proto3" json:"sender_role,omitempty"`
	KnownNodes       []*HeartbeatNodeEntry  `protobuf:"bytes,3,rep,name=known_nodes,json=knownNodes,proto3" json:"known_nodes,omitempty"`
	Stats            map[string]uint64      `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StorageFreeBytes uint64                 `protobuf:"varint,5,opt,name=storage_free_bytes,json=storageFreeBytes,proto3" json:"storage_free_bytes,omitempty"`
	CustomFields     map[string][]byte      `protobuf:"bytes,6,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatPayload) Reset() {
	*x = HeartbeatPayload{}
	mi := &file_proto_carrier_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPayload) ProtoMessage() {}

func (x *HeartbeatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPayload.ProtoReflect.Descriptor instead.
func (*HeartbeatPayload) Descriptor() ([]byte, []int) {
	return file_proto_carrier_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatPayload) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *HeartbeatPayload) GetSenderRole() int32 {
	if x != nil {
		return x.SenderRole
	}
	return 0
}

func (x *HeartbeatPayload) GetKnownNodes() []*HeartbeatNodeEntry {
	if x != nil {
		return x.KnownNodes
	}
	return nil
}

func (x *HeartbeatPayload) GetStats() map[string]uint64 {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *HeartbeatPayload) GetStorageFreeBytes() uint64 {
	if x != nil {
		return x.StorageFreeBytes
	}
	return 0
}

func (x *HeartbeatPayload) GetCustomFields() map[string][]byte {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

var File_proto_carrier_heartbeat_proto protoreflect.FileDescriptor

const file_proto_carrier_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/carrier/heartbeat.proto\x12\acarrier\"_\n" +
	"\x12HeartbeatNodeEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"\xca\x03\n" +
	"\x10HeartbeatPayload\x12 \n" +
	"\fsent_at_unix\x18\x01 \x01(\x03R\n" +
	"sentAtUnix\x12\x1f\n" +
	"\vsender_role\x18\x02 \x01(\x05R\n" +
	"senderRole\x12<\n" +
	"\vknown_nodes\x18\x03 \x03(\v2\x1b.carrier.HeartbeatNodeEntryR\n" +
	"knownNodes\x12:\n" +
	"\x05stats\x18\x04 \x03(\v2$.carrier.HeartbeatPayload.StatsEntryR\x05stats\x12,\n" +
	"\x12storage_free_bytes\x18\x05 \x01(\x04R\x10storageFreeBytes\x12P\n" +
	"\rcustom_fields\x18\x06 \x03(\v2+.carrier.HeartbeatPayload.CustomFieldsEntryR\fcustomFields\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B-Z+github.com/i5heu/ouroboros-db/proto/carrierb\x06proto3"

var (
	file_proto_carrier_heartbeat_proto_rawDescOnce sync.Once
	file_proto_carrier_heartbeat_proto_rawDescData []byte
)

func file_proto_carrier_heartbeat_proto_rawDescGZIP() []byte {
	file_proto_carrier_heartbeat_proto_rawDescOnce.Do(func() {
		file_proto_carrier_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_carrier_heartbeat_proto_rawDesc), len(file_proto_carrier_heartbeat_proto_rawDesc)))
	})
	return file_proto_carrier_heartbeat_proto_rawDescData
}

var file_proto_carrier_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_carrier_heartbeat_proto_goTypes = []any{
	(*HeartbeatNodeEntry)(nil), // 0: carrier.HeartbeatNodeEntry
	(*HeartbeatPayload)(nil),   // 1: carrier.HeartbeatPayload
	nil,                        // 2: carrier.HeartbeatPayload.StatsEntry
	nil,                        // 3: carrier.HeartbeatPayload.CustomFieldsEntry
}
var file_proto_carrier_heartbeat_proto_depIdxs = []int32{
	0, // 0: carrier.HeartbeatPayload.known_nodes:type_name -> carrier.HeartbeatNodeEntry
	2, // 1: carrier.HeartbeatPayload.stats:type_name -> carrier.HeartbeatPayload.StatsEntry
	3, // 2: carrier.HeartbeatPayload.custom_fields:type_name -> carrier.HeartbeatPayload.CustomFieldsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_carrier_heartbeat_proto_init() }
func file_proto_carrier_heartbeat_proto_init() {
	if File_proto_carrier_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_carrier_heartbeat_proto_rawDesc), len(file_proto_carrier_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_carrier_heartbeat_proto_goTypes,
		DependencyIndexes: file_proto_carrier_heartbeat_proto_depIdxs,
		MessageInfos:      file_proto_carrier_heartbeat_proto_msgTypes,
	}.Build()
	File_proto_carrier_heartbeat_proto = out.File
	file_proto_carrier_heartbeat_proto_goTypes = nil
	file_proto_carrier_heartbeat_proto_depIdxs = nil
}
