// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/carrier/message_reply.proto

package carrier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReply) Reset() {
	*x = MessageReply{}
	mi := &file_proto_carrier_message_reply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReply) ProtoMessage() {}

func (x *MessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_message_reply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReply.ProtoReflect.Descriptor instead.
func (*MessageReply) Descriptor() ([]byte, []int) {
	return file_proto_carrier_message_reply_proto_rawDescGZIP(), []int{0}
}

func (x *MessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageReply) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_carrier_message_reply_proto protoreflect.FileDescriptor

const file_proto_carrier_message_reply_proto_rawDesc = "" +
	"\n" +
	"!proto/carrier/message_reply.proto\x12\acarrier\"X\n" +
	"\fMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB-Z+github.com/i5heu/ouroboros-db/proto/carrierb\x06proto3"

var (
	file_proto_carrier_message_reply_proto_rawDescOnce sync.Once
	file_proto_carrier_message_reply_proto_rawDescData []byte
)

func file_proto_carrier_message_reply_proto_rawDescGZIP() []byte {
	file_proto_carrier_message_reply_proto_rawDescOnce.Do(func() {
		file_proto_carrier_message_reply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_carrier_message_reply_proto_rawDesc), len(file_proto_carrier_message_reply_proto_rawDesc)))
	})
	return file_proto_carrier_message_reply_proto_rawDescData
}

var file_proto_carrier_message_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_carrier_message_reply_proto_goTypes = []any{
	(*MessageReply)(nil), // 0: carrier.MessageReply
}
var file_proto_carrier_message_reply_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_carrier_message_reply_proto_init() }
func file_proto_carrier_message_reply_proto_init() {
	if File_proto_carrier_message_reply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_carrier_message_reply_proto_rawDesc), len(file_proto_carrier_message_reply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_carrier_message_reply_proto_goTypes,
		DependencyIndexes: file_proto_carrier_message_reply_proto_depIdxs,
		MessageInfos:      file_proto_carrier_message_reply_proto_msgTypes,
	}.Build()
	File_proto_carrier_message_reply_proto = out.File
	file_proto_carrier_message_reply_proto_goTypes = nil
	file_proto_carrier_message_reply_proto_depIdxs = nil
}
