// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/carrier/user_message.proto

package carrier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_proto_carrier_user_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_user_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_proto_carrier_user_message_proto_rawDescGZIP(), []int{0}
}

func (x *UserMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *UserMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UserMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessageResponse) Reset() {
	*x = UserMessageResponse{}
	mi := &file_proto_carrier_user_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessageResponse) ProtoMessage() {}

func (x *UserMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_user_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessageResponse.ProtoReflect.Descriptor instead.
func (*UserMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_carrier_user_message_proto_rawDescGZIP(), []int{1}
}

func (x *UserMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResponseEmptyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEmptyPayload) Reset() {
	*x = ResponseEmptyPayload{}
	mi := &file_proto_carrier_user_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEmptyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEmptyPayload) ProtoMessage() {}

func (x *ResponseEmptyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carrier_user_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEmptyPayload.ProtoReflect.Descriptor instead.
func (*ResponseEmptyPayload) Descriptor() ([]byte, []int) {
	return file_proto_carrier_user_message_proto_rawDescGZIP(), []int{2}
}

var File_proto_carrier_user_message_proto protoreflect.FileDescriptor

const file_proto_carrier_user_message_proto_rawDesc = "" +
	"\n" +
	" proto/carrier/user_message.proto\x12\acarrier\"5\n" +
	"\vUserMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"/\n" +
	"\x13UserMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14ResponseEmptyPayloadB-Z+github.com/i5heu/ouroboros-db/proto/carrierb\x06proto3"

var (
	file_proto_carrier_user_message_proto_rawDescOnce sync.Once
	file_proto_carrier_user_message_proto_rawDescData []byte
)

func file_proto_carrier_user_message_proto_rawDescGZIP() []byte {
	file_proto_carrier_user_message_proto_rawDescOnce.Do(func() {
		file_proto_carrier_user_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_carrier_user_message_proto_rawDesc), len(file_proto_carrier_user_message_proto_rawDesc)))
	})
	return file_proto_carrier_user_message_proto_rawDescData
}

var file_proto_carrier_user_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_carrier_user_message_proto_goTypes = []any{
	(*UserMessage)(nil),          // 0: carrier.UserMessage
	(*UserMessageResponse)(nil),  // 1: carrier.UserMessageResponse
	(*ResponseEmptyPayload)(nil), // 2: carrier.ResponseEmptyPayload
}
var file_proto_carrier_user_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_carrier_user_message_proto_init() }
func file_proto_carrier_user_message_proto_init() {
	if File_proto_carrier_user_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_carrier_user_message_proto_rawDesc), len(file_proto_carrier_user_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_carrier_user_message_proto_goTypes,
		DependencyIndexes: file_proto_carrier_user_message_proto_depIdxs,
		MessageInfos:      file_proto_carrier_user_message_proto_msgTypes,
	}.Build()
	File_proto_carrier_user_message_proto = out.File
	file_proto_carrier_user_message_proto_goTypes = nil
	file_proto_carrier_user_message_proto_depIdxs = nil
}
