// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/auth/canonical.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanonicalCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertVersion   uint32                 `protobuf:"varint,1,opt,name=cert_version,json=certVersion,proto3" json:"cert_version,omitempty"`
	NodePubKey    []byte                 `protobuf:"bytes,2,opt,name=node_pub_key,json=nodePubKey,proto3" json:"node_pub_key,omitempty"`
	IssuerCaHash  string                 `protobuf:"bytes,3,opt,name=issuer_ca_hash,json=issuerCaHash,proto3" json:"issuer_ca_hash,omitempty"`
	ValidFrom     int64                  `protobuf:"varint,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil    int64                  `protobuf:"varint,5,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Serial        []byte                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	CertNonce     []byte                 `protobuf:"bytes,7,opt,name=cert_nonce,json=certNonce,proto3" json:"cert_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalCert) Reset() {
	*x = CanonicalCert{}
	mi := &file_proto_auth_canonical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalCert) ProtoMessage() {}

func (x *CanonicalCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_canonical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalCert.ProtoReflect.Descriptor instead.
func (*CanonicalCert) Descriptor() ([]byte, []int) {
	return file_proto_auth_canonical_proto_rawDescGZIP(), []int{0}
}

func (x *CanonicalCert) GetCertVersion() uint32 {
	if x != nil {
		return x.CertVersion
	}
	return 0
}

func (x *CanonicalCert) GetNodePubKey() []byte {
	if x != nil {
		return x.NodePubKey
	}
	return nil
}

func (x *CanonicalCert) GetIssuerCaHash() string {
	if x != nil {
		return x.IssuerCaHash
	}
	return ""
}

func (x *CanonicalCert) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *CanonicalCert) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *CanonicalCert) GetSerial() []byte {
	if x != nil {
		return x.Serial
	}
	return nil
}

func (x *CanonicalCert) GetCertNonce() []byte {
	if x != nil {
		return x.CertNonce
	}
	return nil
}

type CanonicalCertBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certs         [][]byte               `protobuf:"bytes,1,rep,name=certs,proto3" json:"certs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalCertBundle) Reset() {
	*x = CanonicalCertBundle{}
	mi := &file_proto_auth_canonical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalCertBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalCertBundle) ProtoMessage() {}

func (x *CanonicalCertBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_canonical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalCertBundle.ProtoReflect.Descriptor instead.
func (*CanonicalCertBundle) Descriptor() ([]byte, []int) {
	return file_proto_auth_canonical_proto_rawDescGZIP(), []int{1}
}

func (x *CanonicalCertBundle) GetCerts() [][]byte {
	if x != nil {
		return x.Certs
	}
	return nil
}

type CanonicalDelegation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TlsCertPubKeyHash  []byte                 `protobuf:"bytes,1,opt,name=tls_cert_pub_key_hash,json=tlsCertPubKeyHash,proto3" json:"tls_cert_pub_key_hash,omitempty"`
	TlsExporterBinding []byte                 `protobuf:"bytes,2,opt,name=tls_exporter_binding,json=tlsExporterBinding,proto3" json:"tls_exporter_binding,omitempty"`
	TlsTranscriptHash  []byte                 `protobuf:"bytes,3,opt,name=tls_transcript_hash,json=tlsTranscriptHash,proto3" json:"tls_transcript_hash,omitempty"`
	X509Fingerprint    []byte                 `protobuf:"bytes,4,opt,name=x509_fingerprint,json=x509Fingerprint,proto3" json:"x509_fingerprint,omitempty"`
	NodeCertBundleHash []byte                 `protobuf:"bytes,5,opt,name=node_cert_bundle_hash,json=nodeCertBundleHash,proto3" json:"node_cert_bundle_hash,omitempty"`
	NotBefore          int64                  `protobuf:"varint,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter           int64                  `protobuf:"varint,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CanonicalDelegation) Reset() {
	*x = CanonicalDelegation{}
	mi := &file_proto_auth_canonical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalDelegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalDelegation) ProtoMessage() {}

func (x *CanonicalDelegation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_canonical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalDelegation.ProtoReflect.Descriptor instead.
func (*CanonicalDelegation) Descriptor() ([]byte, []int) {
	return file_proto_auth_canonical_proto_rawDescGZIP(), []int{2}
}

func (x *CanonicalDelegation) GetTlsCertPubKeyHash() []byte {
	if x != nil {
		return x.TlsCertPubKeyHash
	}
	return nil
}

func (x *CanonicalDelegation) GetTlsExporterBinding() []byte {
	if x != nil {
		return x.TlsExporterBinding
	}
	return nil
}

func (x *CanonicalDelegation) GetTlsTranscriptHash() []byte {
	if x != nil {
		return x.TlsTranscriptHash
	}
	return nil
}

func (x *CanonicalDelegation) GetX509Fingerprint() []byte {
	if x != nil {
		return x.X509Fingerprint
	}
	return nil
}

func (x *CanonicalDelegation) GetNodeCertBundleHash() []byte {
	if x != nil {
		return x.NodeCertBundleHash
	}
	return nil
}

func (x *CanonicalDelegation) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *CanonicalDelegation) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

type CanonicalDelegationNoExporter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TlsCertPubKeyHash  []byte                 `protobuf:"bytes,1,opt,name=tls_cert_pub_key_hash,json=tlsCertPubKeyHash,proto3" json:"tls_cert_pub_key_hash,omitempty"`
	TlsTranscriptHash  []byte                 `protobuf:"bytes,3,opt,name=tls_transcript_hash,json=tlsTranscriptHash,proto3" json:"tls_transcript_hash,omitempty"`
	X509Fingerprint    []byte                 `protobuf:"bytes,4,opt,name=x509_fingerprint,json=x509Fingerprint,proto3" json:"x509_fingerprint,omitempty"`
	NodeCertBundleHash []byte                 `protobuf:"bytes,5,opt,name=node_cert_bundle_hash,json=nodeCertBundleHash,proto3" json:"node_cert_bundle_hash,omitempty"`
	NotBefore          int64                  `protobuf:"varint,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter           int64                  `protobuf:"varint,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CanonicalDelegationNoExporter) Reset() {
	*x = CanonicalDelegationNoExporter{}
	mi := &file_proto_auth_canonical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalDelegationNoExporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalDelegationNoExporter) ProtoMessage() {}

func (x *CanonicalDelegationNoExporter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_canonical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalDelegationNoExporter.ProtoReflect.Descriptor instead.
func (*CanonicalDelegationNoExporter) Descriptor() ([]byte, []int) {
	return file_proto_auth_canonical_proto_rawDescGZIP(), []int{3}
}

func (x *CanonicalDelegationNoExporter) GetTlsCertPubKeyHash() []byte {
	if x != nil {
		return x.TlsCertPubKeyHash
	}
	return nil
}

func (x *CanonicalDelegationNoExporter) GetTlsTranscriptHash() []byte {
	if x != nil {
		return x.TlsTranscriptHash
	}
	return nil
}

func (x *CanonicalDelegationNoExporter) GetX509Fingerprint() []byte {
	if x != nil {
		return x.X509Fingerprint
	}
	return nil
}

func (x *CanonicalDelegationNoExporter) GetNodeCertBundleHash() []byte {
	if x != nil {
		return x.NodeCertBundleHash
	}
	return nil
}

func (x *CanonicalDelegationNoExporter) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *CanonicalDelegationNoExporter) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

var File_proto_auth_canonical_proto protoreflect.FileDescriptor

const file_proto_auth_canonical_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/auth/canonical.proto\x12\x04auth\"\xf1\x01\n" +
	"\rCanonicalCert\x12!\n" +
	"\fcert_version\x18\x01 \x01(\rR\vcertVersion\x12 \n" +
	"\fnode_pub_key\x18\x02 \x01(\fR\n" +
	"nodePubKey\x12$\n" +
	"\x0eissuer_ca_hash\x18\x03 \x01(\tR\fissuerCaHash\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x05 \x01(\x03R\n" +
	"validUntil\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\fR\x06serial\x12\x1d\n" +
	"\n" +
	"cert_nonce\x18\a \x01(\fR\tcertNonce\"+\n" +
	"\x13CanonicalCertBundle\x12\x14\n" +
	"\x05certs\x18\x01 \x03(\fR\x05certs\"\xc3\x02\n" +
	"\x13CanonicalDelegation\x120\n" +
	"\x15tls_cert_pub_key_hash\x18\x01 \x01(\fR\x11tlsCertPubKeyHash\x120\n" +
	"\x14tls_exporter_binding\x18\x02 \x01(\fR\x12tlsExporterBinding\x12.\n" +
	"\x13tls_transcript_hash\x18\x03 \x01(\fR\x11tlsTranscriptHash\x12)\n" +
	"\x10x509_fingerprint\x18\x04 \x01(\fR\x0fx509Fingerprint\x121\n" +
	"\x15node_cert_bundle_hash\x18\x05 \x01(\fR\x12nodeCertBundleHash\x12\x1d\n" +
	"\n" +
	"not_before\x18\x06 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\a \x01(\x03R\bnotAfter\"\x9b\x02\n" +
	"\x1dCanonicalDelegationNoExporter\x120\n" +
	"\x15tls_cert_pub_key_hash\x18\x01 \x01(\fR\x11tlsCertPubKeyHash\x12.\n" +
	"\x13tls_transcript_hash\x18\x03 \x01(\fR\x11tlsTranscriptHash\x12)\n" +
	"\x10x509_fingerprint\x18\x04 \x01(\fR\x0fx509Fingerprint\x121\n" +
	"\x15node_cert_bundle_hash\x18\x05 \x01(\fR\x12nodeCertBundleHash\x12\x1d\n" +
	"\n" +
	"not_before\x18\x06 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\a \x01(\x03R\bnotAfterB*Z(github.com/i5heu/ouroboros-db/proto/authb\x06proto3"

var (
	file_proto_auth_canonical_proto_rawDescOnce sync.Once
	file_proto_auth_canonical_proto_rawDescData []byte
)

func file_proto_auth_canonical_proto_rawDescGZIP() []byte {
	file_proto_auth_canonical_proto_rawDescOnce.Do(func() {
		file_proto_auth_canonical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_canonical_proto_rawDesc), len(file_proto_auth_canonical_proto_rawDesc)))
	})
	return file_proto_auth_canonical_proto_rawDescData
}

var file_proto_auth_canonical_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_auth_canonical_proto_goTypes = []any{
	(*CanonicalCert)(nil),                 // 0: auth.CanonicalCert
	(*CanonicalCertBundle)(nil),           // 1: auth.CanonicalCertBundle
	(*CanonicalDelegation)(nil),           // 2: auth.CanonicalDelegation
	(*CanonicalDelegationNoExporter)(nil), // 3: auth.CanonicalDelegationNoExporter
}
var file_proto_auth_canonical_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_canonical_proto_init() }
func file_proto_auth_canonical_proto_init() {
	if File_proto_auth_canonical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_canonical_proto_rawDesc), len(file_proto_auth_canonical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_auth_canonical_proto_goTypes,
		DependencyIndexes: file_proto_auth_canonical_proto_depIdxs,
		MessageInfos:      file_proto_auth_canonical_proto_msgTypes,
	}.Build()
	File_proto_auth_canonical_proto = out.File
	file_proto_auth_canonical_proto_goTypes = nil
	file_proto_auth_canonical_proto_depIdxs = nil
}
