// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/localSealedSliceStorepb/metadata.proto

package localSealedSliceStorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SliceMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash       []byte                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	PubKeyHash      []byte                 `protobuf:"bytes,2,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"`
	SealedSliceHash []byte                 `protobuf:"bytes,3,opt,name=sealed_slice_hash,json=sealedSliceHash,proto3" json:"sealed_slice_hash,omitempty"`
	RsDataSlices    uint32                 `protobuf:"varint,4,opt,name=rs_data_slices,json=rsDataSlices,proto3" json:"rs_data_slices,omitempty"`
	RsParitySlices  uint32                 `protobuf:"varint,5,opt,name=rs_parity_slices,json=rsParitySlices,proto3" json:"rs_parity_slices,omitempty"`
	RsSliceIndex    uint32                 `protobuf:"varint,6,opt,name=rs_slice_index,json=rsSliceIndex,proto3" json:"rs_slice_index,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SliceMetadata) Reset() {
	*x = SliceMetadata{}
	mi := &file_internal_localSealedSliceStorepb_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceMetadata) ProtoMessage() {}

func (x *SliceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_localSealedSliceStorepb_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceMetadata.ProtoReflect.Descriptor instead.
func (*SliceMetadata) Descriptor() ([]byte, []int) {
	return file_internal_localSealedSliceStorepb_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SliceMetadata) GetChunkHash() []byte {
	if x != nil {
		return x.ChunkHash
	}
	return nil
}

func (x *SliceMetadata) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

func (x *SliceMetadata) GetSealedSliceHash() []byte {
	if x != nil {
		return x.SealedSliceHash
	}
	return nil
}

func (x *SliceMetadata) GetRsDataSlices() uint32 {
	if x != nil {
		return x.RsDataSlices
	}
	return 0
}

func (x *SliceMetadata) GetRsParitySlices() uint32 {
	if x != nil {
		return x.RsParitySlices
	}
	return 0
}

func (x *SliceMetadata) GetRsSliceIndex() uint32 {
	if x != nil {
		return x.RsSliceIndex
	}
	return 0
}

func (x *SliceMetadata) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_internal_localSealedSliceStorepb_metadata_proto protoreflect.FileDescriptor

const file_internal_localSealedSliceStorepb_metadata_proto_rawDesc = "" +
	"\n" +
	"/internal/localSealedSliceStorepb/metadata.proto\x12\x17localSealedSliceStorepb\"\x88\x02\n" +
	"\rSliceMetadata\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\fR\tchunkHash\x12 \n" +
	"\fpub_key_hash\x18\x02 \x01(\fR\n" +
	"pubKeyHash\x12*\n" +
	"\x11sealed_slice_hash\x18\x03 \x01(\fR\x0fsealedSliceHash\x12$\n" +
	"\x0ers_data_slices\x18\x04 \x01(\rR\frsDataSlices\x12(\n" +
	"\x10rs_parity_slices\x18\x05 \x01(\rR\x0ersParitySlices\x12$\n" +
	"\x0ers_slice_index\x18\x06 \x01(\rR\frsSliceIndex\x12\x14\n" +
	"\x05nonce\x18\a \x01(\fR\x05nonceBXZVgithub.com/i5heu/ouroboros-db/internal/localSealedSliceStorepb;localSealedSliceStorepbb\x06proto3"

var (
	file_internal_localSealedSliceStorepb_metadata_proto_rawDescOnce sync.Once
	file_internal_localSealedSliceStorepb_metadata_proto_rawDescData []byte
)

func file_internal_localSealedSliceStorepb_metadata_proto_rawDescGZIP() []byte {
	file_internal_localSealedSliceStorepb_metadata_proto_rawDescOnce.Do(func() {
		file_internal_localSealedSliceStorepb_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_localSealedSliceStorepb_metadata_proto_rawDesc), len(file_internal_localSealedSliceStorepb_metadata_proto_rawDesc)))
	})
	return file_internal_localSealedSliceStorepb_metadata_proto_rawDescData
}

var file_internal_localSealedSliceStorepb_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_localSealedSliceStorepb_metadata_proto_goTypes = []any{
	(*SliceMetadata)(nil), // 0: localSealedSliceStorepb.SliceMetadata
}
var file_internal_localSealedSliceStorepb_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_localSealedSliceStorepb_metadata_proto_init() }
func file_internal_localSealedSliceStorepb_metadata_proto_init() {
	if File_internal_localSealedSliceStorepb_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_localSealedSliceStorepb_metadata_proto_rawDesc), len(file_internal_localSealedSliceStorepb_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_localSealedSliceStorepb_metadata_proto_goTypes,
		DependencyIndexes: file_internal_localSealedSliceStorepb_metadata_proto_depIdxs,
		MessageInfos:      file_internal_localSealedSliceStorepb_metadata_proto_msgTypes,
	}.Build()
	File_internal_localSealedSliceStorepb_metadata_proto = out.File
	file_internal_localSealedSliceStorepb_metadata_proto_goTypes = nil
	file_internal_localSealedSliceStorepb_metadata_proto_depIdxs = nil
}
