// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/authfile/authfile.proto

package authfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CAKeyFile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	KeyJson            []byte                 `protobuf:"bytes,2,opt,name=key_json,json=keyJson,proto3" json:"key_json,omitempty"`
	AnchorSig          []byte                 `protobuf:"bytes,3,opt,name=anchor_sig,json=anchorSig,proto3" json:"anchor_sig,omitempty"`
	AnchorAdmin        string                 `protobuf:"bytes,4,opt,name=anchor_admin,json=anchorAdmin,proto3" json:"anchor_admin,omitempty"`
	AnchorAdminPubKem  []byte                 `protobuf:"bytes,5,opt,name=anchor_admin_pub_kem,json=anchorAdminPubKem,proto3" json:"anchor_admin_pub_kem,omitempty"`
	AnchorAdminPubSign []byte                 `protobuf:"bytes,6,opt,name=anchor_admin_pub_sign,json=anchorAdminPubSign,proto3" json:"anchor_admin_pub_sign,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CAKeyFile) Reset() {
	*x = CAKeyFile{}
	mi := &file_proto_authfile_authfile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAKeyFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAKeyFile) ProtoMessage() {}

func (x *CAKeyFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authfile_authfile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAKeyFile.ProtoReflect.Descriptor instead.
func (*CAKeyFile) Descriptor() ([]byte, []int) {
	return file_proto_authfile_authfile_proto_rawDescGZIP(), []int{0}
}

func (x *CAKeyFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CAKeyFile) GetKeyJson() []byte {
	if x != nil {
		return x.KeyJson
	}
	return nil
}

func (x *CAKeyFile) GetAnchorSig() []byte {
	if x != nil {
		return x.AnchorSig
	}
	return nil
}

func (x *CAKeyFile) GetAnchorAdmin() string {
	if x != nil {
		return x.AnchorAdmin
	}
	return ""
}

func (x *CAKeyFile) GetAnchorAdminPubKem() []byte {
	if x != nil {
		return x.AnchorAdminPubKem
	}
	return nil
}

func (x *CAKeyFile) GetAnchorAdminPubSign() []byte {
	if x != nil {
		return x.AnchorAdminPubSign
	}
	return nil
}

type EmbeddedCAFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PubKem        []byte                 `protobuf:"bytes,2,opt,name=pub_kem,json=pubKem,proto3" json:"pub_kem,omitempty"`
	PubSign       []byte                 `protobuf:"bytes,3,opt,name=pub_sign,json=pubSign,proto3" json:"pub_sign,omitempty"`
	AnchorSig     []byte                 `protobuf:"bytes,4,opt,name=anchor_sig,json=anchorSig,proto3" json:"anchor_sig,omitempty"`
	AnchorAdmin   string                 `protobuf:"bytes,5,opt,name=anchor_admin,json=anchorAdmin,proto3" json:"anchor_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddedCAFile) Reset() {
	*x = EmbeddedCAFile{}
	mi := &file_proto_authfile_authfile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedCAFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedCAFile) ProtoMessage() {}

func (x *EmbeddedCAFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authfile_authfile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedCAFile.ProtoReflect.Descriptor instead.
func (*EmbeddedCAFile) Descriptor() ([]byte, []int) {
	return file_proto_authfile_authfile_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddedCAFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmbeddedCAFile) GetPubKem() []byte {
	if x != nil {
		return x.PubKem
	}
	return nil
}

func (x *EmbeddedCAFile) GetPubSign() []byte {
	if x != nil {
		return x.PubSign
	}
	return nil
}

func (x *EmbeddedCAFile) GetAnchorSig() []byte {
	if x != nil {
		return x.AnchorSig
	}
	return nil
}

func (x *EmbeddedCAFile) GetAnchorAdmin() string {
	if x != nil {
		return x.AnchorAdmin
	}
	return ""
}

type NodeCertFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	KeyJson       []byte                 `protobuf:"bytes,2,opt,name=key_json,json=keyJson,proto3" json:"key_json,omitempty"`
	CaPubKem      []byte                 `protobuf:"bytes,3,opt,name=ca_pub_kem,json=caPubKem,proto3" json:"ca_pub_kem,omitempty"`
	CaPubSign     []byte                 `protobuf:"bytes,4,opt,name=ca_pub_sign,json=caPubSign,proto3" json:"ca_pub_sign,omitempty"`
	CaSignature   []byte                 `protobuf:"bytes,5,opt,name=ca_signature,json=caSignature,proto3" json:"ca_signature,omitempty"`
	Authorities   []*EmbeddedCAFile      `protobuf:"bytes,6,rep,name=authorities,proto3" json:"authorities,omitempty"`
	IssuerCaHash  string                 `protobuf:"bytes,7,opt,name=issuer_ca_hash,json=issuerCaHash,proto3" json:"issuer_ca_hash,omitempty"`
	ValidFrom     int64                  `protobuf:"varint,8,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil    int64                  `protobuf:"varint,9,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Serial        []byte                 `protobuf:"bytes,10,opt,name=serial,proto3" json:"serial,omitempty"`
	CertNonce     []byte                 `protobuf:"bytes,11,opt,name=cert_nonce,json=certNonce,proto3" json:"cert_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCertFile) Reset() {
	*x = NodeCertFile{}
	mi := &file_proto_authfile_authfile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCertFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCertFile) ProtoMessage() {}

func (x *NodeCertFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authfile_authfile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCertFile.ProtoReflect.Descriptor instead.
func (*NodeCertFile) Descriptor() ([]byte, []int) {
	return file_proto_authfile_authfile_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCertFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeCertFile) GetKeyJson() []byte {
	if x != nil {
		return x.KeyJson
	}
	return nil
}

func (x *NodeCertFile) GetCaPubKem() []byte {
	if x != nil {
		return x.CaPubKem
	}
	return nil
}

func (x *NodeCertFile) GetCaPubSign() []byte {
	if x != nil {
		return x.CaPubSign
	}
	return nil
}

func (x *NodeCertFile) GetCaSignature() []byte {
	if x != nil {
		return x.CaSignature
	}
	return nil
}

func (x *NodeCertFile) GetAuthorities() []*EmbeddedCAFile {
	if x != nil {
		return x.Authorities
	}
	return nil
}

func (x *NodeCertFile) GetIssuerCaHash() string {
	if x != nil {
		return x.IssuerCaHash
	}
	return ""
}

func (x *NodeCertFile) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *NodeCertFile) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *NodeCertFile) GetSerial() []byte {
	if x != nil {
		return x.Serial
	}
	return nil
}

func (x *NodeCertFile) GetCertNonce() []byte {
	if x != nil {
		return x.CertNonce
	}
	return nil
}

var File_proto_authfile_authfile_proto protoreflect.FileDescriptor

const file_proto_authfile_authfile_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/authfile/authfile.proto\x12\bauthfile\"\xe0\x01\n" +
	"\tCAKeyFile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bkey_json\x18\x02 \x01(\fR\akeyJson\x12\x1d\n" +
	"\n" +
	"anchor_sig\x18\x03 \x01(\fR\tanchorSig\x12!\n" +
	"\fanchor_admin\x18\x04 \x01(\tR\vanchorAdmin\x12/\n" +
	"\x14anchor_admin_pub_kem\x18\x05 \x01(\fR\x11anchorAdminPubKem\x121\n" +
	"\x15anchor_admin_pub_sign\x18\x06 \x01(\fR\x12anchorAdminPubSign\"\x9a\x01\n" +
	"\x0eEmbeddedCAFile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\apub_kem\x18\x02 \x01(\fR\x06pubKem\x12\x19\n" +
	"\bpub_sign\x18\x03 \x01(\fR\apubSign\x12\x1d\n" +
	"\n" +
	"anchor_sig\x18\x04 \x01(\fR\tanchorSig\x12!\n" +
	"\fanchor_admin\x18\x05 \x01(\tR\vanchorAdmin\"\xf7\x02\n" +
	"\fNodeCertFile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bkey_json\x18\x02 \x01(\fR\akeyJson\x12\x1c\n" +
	"\n" +
	"ca_pub_kem\x18\x03 \x01(\fR\bcaPubKem\x12\x1e\n" +
	"\vca_pub_sign\x18\x04 \x01(\fR\tcaPubSign\x12!\n" +
	"\fca_signature\x18\x05 \x01(\fR\vcaSignature\x12:\n" +
	"\vauthorities\x18\x06 \x03(\v2\x18.authfile.EmbeddedCAFileR\vauthorities\x12$\n" +
	"\x0eissuer_ca_hash\x18\a \x01(\tR\fissuerCaHash\x12\x1d\n" +
	"\n" +
	"valid_from\x18\b \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\t \x01(\x03R\n" +
	"validUntil\x12\x16\n" +
	"\x06serial\x18\n" +
	" \x01(\fR\x06serial\x12\x1d\n" +
	"\n" +
	"cert_nonce\x18\v \x01(\fR\tcertNonceB.Z,github.com/i5heu/ouroboros-db/proto/authfileb\x06proto3"

var (
	file_proto_authfile_authfile_proto_rawDescOnce sync.Once
	file_proto_authfile_authfile_proto_rawDescData []byte
)

func file_proto_authfile_authfile_proto_rawDescGZIP() []byte {
	file_proto_authfile_authfile_proto_rawDescOnce.Do(func() {
		file_proto_authfile_authfile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authfile_authfile_proto_rawDesc), len(file_proto_authfile_authfile_proto_rawDesc)))
	})
	return file_proto_authfile_authfile_proto_rawDescData
}

var file_proto_authfile_authfile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_authfile_authfile_proto_goTypes = []any{
	(*CAKeyFile)(nil),      // 0: authfile.CAKeyFile
	(*EmbeddedCAFile)(nil), // 1: authfile.EmbeddedCAFile
	(*NodeCertFile)(nil),   // 2: authfile.NodeCertFile
}
var file_proto_authfile_authfile_proto_depIdxs = []int32{
	1, // 0: authfile.NodeCertFile.authorities:type_name -> authfile.EmbeddedCAFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_authfile_authfile_proto_init() }
func file_proto_authfile_authfile_proto_init() {
	if File_proto_authfile_authfile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authfile_authfile_proto_rawDesc), len(file_proto_authfile_authfile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_authfile_authfile_proto_goTypes,
		DependencyIndexes: file_proto_authfile_authfile_proto_depIdxs,
		MessageInfos:      file_proto_authfile_authfile_proto_msgTypes,
	}.Build()
	File_proto_authfile_authfile_proto = out.File
	file_proto_authfile_authfile_proto_goTypes = nil
	file_proto_authfile_authfile_proto_depIdxs = nil
}
